project:
  type: website

website:
  page-navigation: true
  title: "ETF2121/5912 - S2 2024"
  description: "Homepage for ETF2121/5921 - Data Analysis in Business at Monash University, S2 2023."
  site-url: "https://sta210-s22.github.io/website/"


  open-graph: true

  twitter-card:
    creator: "@minebocek"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Dr. Joan Tan"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
      - section: "Weekly Schedule"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual