---
title: "ETF2121/5912: Data Analysis in Business"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| Week                      | Date            | Topic                                                | Prepare      | Slides   | Quiz/Assignments |
+:=========================:+=================+======================================================+:============:+:========:+:================:+
| [1](/weeks/week-1.html)   | Jul 22 - Jul 26 | Tutorial 1 - R & Power BI installation               |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Jul 23     | Welcome to ETF2121/5921!                             |              |          |                  |
|                           |                 |                                                      |              |          |                  |
|                           |                 | Introduction to Data Analysis                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Jul 26     | Released: Tutorial 1 Solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [2](/weeks/week-2.html)   | Jul 29 - Aug 2  | Tutorial 2                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Jul 30     | Description Statistics                               |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Aug 2      | Released: Tutorial 2 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [3](/weeks/week-3.html)   | Aug 5 - Aug 9   | *Tutorial 3*                                         |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Aug 6      | Data Visualization                                   |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Aug 9      | Released: Tutorial 3 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [4](/weeks/week-4.html)   | Aug 12 - Aug 16 | Tutorial 4                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Aug 13     | Data Wrangling                                       |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Aug 16     | Released: Tutorial 4 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [5](/weeks/week-5.html)   | Aug 19 - Aug 23 | Tutorial 5                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Aug 20     | Probabiliy: An Introduction to Modelling Uncertainty |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Aug 23     | Released: Tutorial 5 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [6](/weeks/week-6.html)   | Aug 26 - Aug 30 | Tutorial 6                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Aug 27     | Descriptive Data Mining                              |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Wed, Aug 28     | Individual assignment submission deadline            |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Aug 30     | Released: Tutorial 6 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [7](/weeks/week-7.html)   | Sep 2 - Sep 6   | Tutorial 7                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Sep 3      | Statistical Inference                                |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Sep 6      | Released: Tutorial 7 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [8](/weeks/week-8.html)   | Sep 9 - Sep 13  | Tutorial 8                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Sep 10     | Linear Regression                                    |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Sep 13     | Released: Tutorial 8 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [9](/weeks/week-9.html)   | Sep 16 - Sep 20 | Tutorial 9                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Sep 17     | Time Series Analysis and Forecasting                 |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Sep 20     | Released: Tutorial 9 solution                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| Semester Break            | Sep 23 - Sep 27 | Mid semester break                                   |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [10](/weeks/week-10.html) | Sep 30 - Oct 4  | Tutorial 10                                          |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Oct 1      | Decision Tree                                        |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Thu, Mar 17     | Released: Tutorial 10 solution                       |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [11](/weeks/week-11.html) | Oct 7 - Oct 11  | Tutorial 11                                          |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Oct 8      | Regression                                           |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Wed, Oct 9      | Individual Assignment 2 Submission Deadline          |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Oct 11     | Released: Tutorial 11 solution                       |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| [12](/weeks/week-12.html) | Oct 14 - Oct 18 | Tutorial 12                                          |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Tue, Oct 15     | Classification                                       |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
|                           | Fri, Oct 18     | Released: Tutorial 12 Solution                       |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+
| SWOT                      | Oct 21 - Oct 25 | SWOT                                                 |              |          |                  |
+---------------------------+-----------------+------------------------------------------------------+--------------+----------+------------------+

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project | Quiz |
|-------|-------|-------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |  📝  |
